config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/redmine-plugin-scrum
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

resources :projects do
  resources :sprints, :shallow => true do
    member do
      get :edit_effort
      put :update_effort
      get :burndown
      get :burndown_graph
    end
    collection do
      get :burndown_index
    end
  end
  post "sprints/change_task_status",
       :controller => :sprints, :action => :change_task_status,
       :as => :sprints_change_task_status

  resources :product_backlog, :shallow => true, :only => [:index] do
    collection do
      post :sort
      post :create_pbi
      get :burndown
      get :burndown_graph
      get :check_dependencies
    end
  end
  get "product_backlog/new_pbi/:tracker_id",
      :controller => :product_backlog, :action => :new_pbi,
      :as => :product_backlog_new_pbi

  get "release_plan",
      :controller => :scrum, :action => :release_plan,
      :as => :release_plan

end

post "issues/:id/story_points",
     :controller => :scrum, :action => :change_story_points,
     :as => :change_story_points
post "issues/:id/pending_effort",
     :controller => :scrum, :action => :change_pending_effort,
     :as => :change_pending_effort
post "issues/:id/assigned_to",
     :controller => :scrum, :action => :change_assigned_to,
     :as => :change_assigned_to
post "issues/:id/create_time_entry",
     :controller => :scrum, :action => :create_time_entry,
     :as => :create_time_entry
get "scrum/:sprint_id/new_pbi/:tracker_id",
     :controller => :scrum, :action => :new_pbi,
     :as => :new_pbi
post "scrum/:sprint_id/create_pbi",
     :controller => :scrum, :action => :create_pbi,
     :as => :create_pbi
get "scrum/:pbi_id/new/:tracker_id",
    :controller => :scrum, :action => :new_task,
    :as => :new_task
post "scrum/:pbi_id/create_task",
     :controller => :scrum, :action => :create_task,
     :as => :create_task
get "scrum/:pbi_id/edit_pbi",
    :controller => :scrum, :action => :edit_pbi,
    :as => :edit_pbi
post "scrum/:pbi_id/update_pbi",
     :controller => :scrum, :action => :update_pbi,
     :as => :update_pbi
get "scrum/:id/edit_task",
    :controller => :scrum, :action => :edit_task,
    :as => :edit_task
post "scrum/:id/update_task",
     :controller => :scrum, :action => :update_task,
     :as => :update_task
post "scrum/:pbi_id/move_to_last_sprint",
     :controller => :scrum, :action => :move_to_last_sprint,
     :as => :move_to_last_sprint
post "scrum/:pbi_id/move_to_product_backlog",
     :controller => :scrum, :action => :move_to_product_backlog,
     :as => :move_to_product_backlog

app/views/post_its/sprint_board/_head.html.erb
<table class="box attributes">
  <tr>
    <td>
      <div class="tabular">
        <p>
          <label><%= l(:label_sprint) %>:</label>
          <%- options = project.sprints.collect{|other_sprint| [other_sprint.name, path.call(other_sprint)]}
              options = options_for_select(options, path.call(sprint)) -%>
          <%= select_tag "selected_sprint_id", options,
                         :onchange => "if (this.value != '') { window.location = this.value; }" %>
        </p>
        <p>
          <label><%= l(:field_start_date) %>:</label>
          <%= format_date sprint.sprint_start_date %>
        </p>
        <p>
          <label><%= l(:field_end_date) %>:</label>
          <%= format_date sprint.sprint_end_date %>
        </p>
      </div>
    </td>
    <td>
      <%- if User.current.allowed_to?(:view_sprint_stats, project) -%>
      <div class="tabular">
        <p>
          <label><%= l(:label_sps_by_pbi) %>:</label>
          <%- phs, total = sprint.phs_by_pbi -%>
          <%= phs.collect{|ph| "#{ph[:tracker].name} #{l(:label_sps_stat, :phs => ph[:total], :percentage => ph[:percentage])}"}.concat([l(:label_sps_total, :phs => total)]).join(", ") %>
        </p>
        <p>
          <label><%= l(:label_time_by_activity) %>:</label>
          <%- time_entries, total = sprint.time_entries_by_activity -%>
          <%= time_entries.collect{|activity| "#{activity[:activity].name} #{l(:label_time_stat, :time => activity[:total], :percentage => activity[:percentage])}"}.concat([l(:label_time_total, :time => total)]).join(", ") %>
        </p>
        <%- if User.current.allowed_to?(:view_sprint_stats_by_member, project) -%>
        <p>
          <label><%= l(:label_estimated_effort) %>:</label>
          <%- efforts, total = sprint.efforts_by_member -%>
          <%= raw(efforts.collect{|effort| "#{link_to_user(effort[:member])} #{l(:label_time_stat, :time => effort[:total], :percentage => effort[:percentage])}"}.join(", ")) %>
        </p>
        <p>
          <label><%= l(:label_done_effort) %>:</label>
          <%- time_entries, total = sprint.time_entries_by_member -%>
          <%= raw(time_entries.collect{|activity| "#{link_to_user(activity[:member])} #{l(:label_time_stat, :time => activity[:total], :percentage => activity[:percentage])}"}.join(", ")) %>
        </p>
        <%- end -%>
      </div>
      <%- end -%>
    </td>
  </tr>
  <%- if !(sprint.description.blank?) -%>
  <tr>
    <td colspan="2">
      <hr/>
      <%= raw(Redmine::WikiFormatting::Textile::Formatter.new(sprint.description).to_html(true)) %>
    </td>
  </tr>
  <%- end -%>
</table>

app/views/post_its/sprint_board/_pbi.html.erb
<%- pbi_id = "pbi_#{pbi.id}" -%>
<table id="<%= pbi_id %>" class="<%= pbi.post_it_css_class(:rotate => true, :scale => true) %>">
  <tr>
    <td class="content">
      <%- if User.current.allowed_to?(:edit_sprint_board, project) and 
             User.current.allowed_to?(:edit_issues, project) and
             pbi.editable? and !read_only -%>
        <%= link_to "", edit_pbi_path(pbi),
                    :remote => true, :method => "GET", :class => "icon icon-edit float-icon" %>
      <%- end -%>
      <%= link_to_issue(pbi, :tracker => false, :truncate => 150) %>
    </td>
  </tr>
  <tr>
    <td class="estimation">
      <%- if pbi.has_story_points? -%>
        <%= render :partial => "common/scrum_story_points", :formats => [:html],
                   :locals => {:project => project, :pbi => pbi, :read_only => read_only} %>
        <span title="<%= l(:label_story_point_plural) %>"><%= l(:label_story_point_unit) %></span>
      <%- end -%>
    </td>
  </tr>
</table>

<%= render :partial => "post_its/sprint_board/pbi_context_menu", :formats => [:html],
           :locals => {:project => project,
                       :pbi => pbi,
                       :pbi_id => pbi_id} %>

app/views/post_its/sprint_board/_pbi_context_menu.html.erb
<%- if User.current.allowed_to?(:edit_sprint_board, project) and pbi.editable? -%>
  <%- context_menu_id = "pbi_#{pbi.id}_context_menu"
      new_subtask_link_class = "pbi_#{pbi.id}_new_subtask" -%>
  <div id="<%= context_menu_id %>" class="scrum-custom-menu">
    <%- close_context_menu_pbi_id = "close_context_menu_pbi_#{pbi.id}" -%>
    <%= link_to "", "#", :class => "close-icon contextual", :id => close_context_menu_pbi_id %>

    <fieldset>
      <legend><%= l(:label_create_subtask) %></legend>
      <%- Tracker.task_trackers.each do |tracker| -%>
        <label>
          <%= link_to tracker.name, new_task_path(pbi, tracker),
                      :remote => true, :method => "GET", :class => "icon icon-add #{new_subtask_link_class}" %>
        </label><br/>
      <%- end -%>
    </fieldset>
  </div>

  <%= render :partial => "post_its/sprint_board/pbi_context_menu", :formats => [:js],
             :locals => {:project => project,
                         :pbi => pbi,
                         :pbi_id => pbi_id,
                         :context_menu_id => context_menu_id,
                         :close_context_menu_pbi_id => close_context_menu_pbi_id,
                         :new_subtask_link_class => new_subtask_link_class} %>
<%- end -%>

app/views/post_its/sprint_board/_pbi_context_menu.js.erb
<%- if User.current.allowed_to?(:edit_sprint_board, project) and pbi.editable? -%>
	<%= javascript_tag do %>
		var pbi_context_menu_function = function(event) {
			$(".scrum-custom-menu").hide();
			event.preventDefault();
			var maxX = $(document).width() - $("#<%= context_menu_id %>").width() - 10;
			var maxY = $(document).height() - $("#<%= context_menu_id %>").height() - 10;
			var x = (event.pageX > maxX) ? maxX : event.pageX;
			var y = (event.pageY > maxY) ? maxY : event.pageY;
			$("#<%= context_menu_id %>").css({
				left: x + "px",
				top: y + "px"
			});
			$("#<%= context_menu_id %>").show();
		};
		$("#<%= pbi_id %>").dblclick(pbi_context_menu_function);
		$("#<%= pbi_id %>").contextmenu(pbi_context_menu_function);
		$("#<%= close_context_menu_pbi_id %>").click(function(event) {
			$(".scrum-custom-menu").hide();
		});
		$(".<%= new_subtask_link_class %>").click(function(event) {
			$(".scrum-custom-menu").hide();
		});
	<% end %>
<%- end -%>

app/views/post_its/sprint_board/_pbi_row.html.erb
<tr class="sprint-board" id="<%= "pbi_#{pbi.id}_row" %>">
  <td class="sprint-board">
    <%= render :partial => "post_its/sprint_board/pbi", :formats => [:html],
               :locals => {:project => project, :pbi => pbi, :read_only => false} %>
  </td>
  <%- tasks = pbi.tasks_by_status_id
      task_statuses.each do |status| -%>
    <%- pbi_status_id = "pbi_#{pbi.id}_status_#{status.id}"
        other_pbi_status_ids = task_statuses.select{|other| other != status}.collect{
          |other| "pbi_#{pbi.id}_status_#{other.id}"
        } -%>
    <td id="<%= pbi_status_id %>" class="sprint-board">
      <%- tasks[status.id].each do |task| -%>
        <%= render :partial => "post_its/sprint_board/task", :formats => [:html],
                   :locals => {:project => project,
                               :task => task,
                               :pbi_status_id => pbi_status_id,
                               :other_pbi_status_ids => other_pbi_status_ids,
                               :read_only => false} %>
      <%- end -%>
    </td>
    <%= render :partial => "post_its/sprint_board/pbi_status", :formats => [:js],
               :locals => {:project => project,
                           :pbi_id => pbi.id,
                           :pbi_status_id => pbi_status_id,
                           :status => status} %>
  <%- end -%>
</tr>

app/views/post_its/sprint_board/_pbi_status.js.erb
<%= javascript_tag do %>
	$(document).ready(function() {
		$("#<%= pbi_status_id %>").droppable({
			accept: ".sprint-task",
			drop: function(event, ui) {
				if ($.isFunction($.fn.setupAjaxIndicator)) {
					setupAjaxIndicator();
				}
				if (!(ui.draggable.is($(this).children()))) {
					$.ajax({
						url: "<%= project_sprints_change_task_status_path(@project) %>",
						type: "POST",
						data: {task: encodeURIComponent($(ui.draggable).attr("id")),
									 status: encodeURIComponent("<%= status.id %>")},
						error: function() {
							alert("<%= l(:error_changing_task_status) %>");
							var task = $(ui.draggable);
							task.detach();
							task.appendTo($("#<%= "pbi_#{pbi_id}_status_" %>" + ui.draggable.attr("old-status")));
						},
						complete: function() {
							if ($.isFunction($.fn.hideOnLoad)) {
								hideOnLoad();
							}
						},
						success: function() {
							ui.draggable.attr("old-status", "<%= status.id %>");
							window["container_" + $(ui.draggable).attr("id")] = "";
						}
					});
				}
				ui.draggable.appendTo($(this)).removeAttr("style");
				ui.draggable.attr("style", "position: relative; " + ui.draggable.attr("style"));
			}
		});
	});
<% end %>

app/views/post_its/sprint_board/_task.html.erb
<%- task_id = "task_#{task.id}" -%>
<table id="<%= task_id %>" class="<%= task.post_it_css_class(:rotate => true, :scale => true, :draggable => true) %>"
       old-status="<%= task.status.id %>">
  <tr>
    <td class="content" colspan="3">
      <div class="content">
        <%- if User.current.allowed_to?(:edit_sprint_board, project) and 
               User.current.allowed_to?(:edit_issues, project) and
               task.editable? and !read_only -%>
          <%= link_to "", edit_task_path(task),
                      :remote => true, :method => "GET", :class => "icon icon-edit float-icon" %>
        <%- end -%>
        <%= link_to_issue(task, :tracker => false, :truncate => 100) %>
        <div class="doers-reviewers-post-its-container">
          <%- task.doers.each do |doer| -%>
            <div class="<%= Issue.doer_post_it_css_class %>">
              <%= avatar(doer, :size => "14") %> <%= link_to_user doer %>
            </div>
          <%- end -%>
          <%- task.reviewers.each do |reviewer| -%>
            <div class="<%= Issue.reviewer_post_it_css_class %>">
              <%= avatar(reviewer, :size => "14") %> <%= link_to_user reviewer %>
            </div>
          <%- end -%>
        </div>
      </div>
    </td>
  </tr>
  <tr>
    <td class="estimation">
      <%= render_hours(task.estimated_hours, :title => l(:field_estimated_hours)) %>
    </td>
    <td class="spent">
      <%- if User.current.allowed_to?(:view_time_entries, project) -%>
        <%= render_hours(task.spent_hours, :title => l(:label_spent_time), :ignore_zero => true,
                         :link => respond_to?(:issue_time_entries_path) ?
                                  issue_time_entries_path(task) :
                                  project_issue_time_entries_path(project, task)) %>
      <%- end -%>
    </td>
    <td class="pending">
      <%= render :partial => "common/scrum_pending_effort", :formats => [:html],
                 :locals => {:project => project, :task => task} %>
      <span title="<%= l(:field_pending_effort) %>">h</span>
    </td>
  </tr>
</table>

<%= render :partial => "post_its/sprint_board/task", :formats => [:js],
           :locals => {:project => project,
                       :other_pbi_status_ids => other_pbi_status_ids,
                       :task_id => task_id,
                       :task => task} %>

<%= render :partial => "post_its/sprint_board/task_context_menu", :formats => [:html],
           :locals => {:project => project,
                       :task => task,
                       :pbi_status_id => pbi_status_id,
                       :other_pbi_status_ids => other_pbi_status_ids,
                       :task_id => task_id} %>

app/views/post_its/sprint_board/_task.js.erb
<%- if User.current.allowed_to?(:edit_sprint_board, project) and task.editable? -%>
	<%= javascript_tag do %>
		<%- other_pbi_status_ids.each do |pbi_status_id| -%>
			$(document).ready(function() {
				$("#<%= task_id %>").draggable({
					revert: "invalid",
					axis: "x",
					containment: "<%= pbi_status_id %>",
					cursor: "ew-resize",
					stack: "table"
				});
				draggableOnTouchScreen("<%= task_id %>");
			});
		<%- end -%>
	<% end %>
<%- end -%>

app/views/post_its/sprint_board/_task_context_menu.html.erb
<%- if User.current.allowed_to?(:edit_sprint_board, project) and task.editable? -%>
  <%- context_menu_id = "task_#{task.id}_context_menu"
      context_menu_assigned_to_id = "task_#{task.id}_context_menu_assigned_to"
      time_entry_form_id = "time_entry_form_#{task.id}" -%>
  <div id="<%= context_menu_id %>" class="scrum-custom-menu">
    <%- close_context_menu_task_id = "close_context_menu_task_#{task.id}" -%>
    <%= link_to "", "#", :class => "close-icon contextual", :id => close_context_menu_task_id %>

    <fieldset>
      <legend><%= l(:label_user_plural) %></legend>
      <label><%= l(:field_assigned_to) %>:</label>
      <p>
        <%- members = task.project.members.collect{|member| [member.user.name, member.user.id]}
            members_options = options_for_select(members, task.assigned_to.nil? ? nil : task.assigned_to.id)
            members_select = select_tag context_menu_assigned_to_id, members_options, :include_blank => true
            members_select.gsub(/\n/, "") -%>
          <%= members_select %>
      </p>
    </fieldset>

    <%- if User.current.allowed_to?(:view_time_entries, project) -%>
      <fieldset>
        <legend><%= l(:label_spent_time) %></legend>
        <%= form_for :time_entry,
                     :url => create_time_entry_path(task),
                     :html => {:id => time_entry_form_id} do |f| %>
          <%= hidden_field_tag :pbi_status_id, pbi_status_id %>
          <%= hidden_field_tag :other_pbi_status_ids, other_pbi_status_ids.join(",") %>

          <label><%= l(:field_hours) %>:</label>
          <p><%= f.text_field :hours, :size => 15, :required => true %></p>

          <label><%= l(:field_spent_on) %>:</label>
          <p>
            <%= f.text_field :spent_on, :size => 10, :value => Date.today, :required => true %>
            <%= calendar_for(:time_entry_spent_on) %>
          </p>

          <label><%= l(:field_comments) %>:</label>
          <p><%= f.text_field :comments, :size => 15, :maxlength => 255 %></p>

          <label><%= l(:field_activity) %>:</label>
          <p><%= f.select :activity_id,
                          project.activities.collect{|activity| [activity.name, activity.id]},
                          :required => true %></p>

          <label><%= l(:field_user) %>:</label>
          <p><%= f.select :user_id,
                          principals_options_for_select(task.assignable_users, task.assigned_to),
                          :required => true %></p>

          <%- TimeEntry.new.custom_field_values.each do |value| -%>
            <label><%= value.custom_field.name %>:</label>
            <p><%= custom_field_tag :time_entry, value %></p>
          <%- end -%>

          <p><%= submit_tag l(:button_save) %></p>
        <% end %>
      </fieldset>
    <%- end -%>
    <%= render :partial => "post_its/sprint_board/task_context_menu", :formats => [:js],
               :locals => {:project => project,
                           :pbi_status_id => pbi_status_id,
                           :other_pbi_status_ids => other_pbi_status_ids,
                           :task_id => task_id,
                           :task => task,
                           :context_menu_id => context_menu_id,
                           :context_menu_assigned_to_id => context_menu_assigned_to_id,
                           :close_context_menu_task_id => close_context_menu_task_id,
                           :time_entry_form_id => time_entry_form_id} %>
  </div>
<%- end -%>

app/views/post_its/sprint_board/_task_context_menu.js.erb
<%- if User.current.allowed_to?(:edit_sprint_board, project) and task.editable? -%>
	<%= javascript_tag do %>
		var task_context_menu_function = function(event) {
			$(".scrum-custom-menu").hide();
			event.preventDefault();
			var maxX = $(document).width() - $("#<%= context_menu_id %>").width() - 10;
			var maxY = $(document).height() - $("#<%= context_menu_id %>").height() - 10;
			var x = (event.pageX > maxX) ? maxX : event.pageX;
			var y = (event.pageY > maxY) ? maxY : event.pageY;
			$("#<%= context_menu_id %>").css({
				left: x + "px",
				top: y + "px"
			});
			$("#<%= context_menu_id %>").show();
		};
		$("#<%= task_id %>").dblclick(task_context_menu_function);
		$("#<%= task_id %>").contextmenu(task_context_menu_function);
		$("#<%= close_context_menu_task_id %>").click(function(event) {
			$(".scrum-custom-menu").hide();
		});
		$("#<%= context_menu_assigned_to_id %>").change(function() {
			$.ajax({
				url: "<%= change_assigned_to_path(task) %>",
				type: "POST",
				data: {value: $(this).val(),
							 pbi_status_id: "<%= pbi_status_id %>",
							 other_pbi_status_ids: "<%= other_pbi_status_ids.join(",") %>",
							 task_id: "<%= task_id %>"},
				error: function() {
					alert("<%= l(:error_changing_task_assigned_to) %>");
				},
				complete: function() {
					$(".scrum-custom-menu").hide();
					if ($.isFunction($.fn.hideOnLoad)) {
						hideOnLoad();
					}
				},
				success: function(data) {
					$("#<%= task_id %>").replaceWith(data);
				}
			});
		});
		<%- sending_time_entry = "sending_time_entry_#{time_entry_form_id}" -%>
		var <%= sending_time_entry %> = false;
		$("#<%= time_entry_form_id %>").submit(function() {
			if (!<%= sending_time_entry %>) {
				<%= sending_time_entry %> = true;
				var values = $(this).serialize();
				$.ajax({
					url: $(this).attr("action"),
					type: "POST",
					data: values,
					error: function() {
						alert("<%= l(:error_creating_time_entry) %>");
					},
					complete: function() {
						$(".scrum-custom-menu").hide();
						if ($.isFunction($.fn.hideOnLoad)) {
							hideOnLoad();
						}
						<%= sending_time_entry %> = false;
					},
					success: function(data) {
						$("#<%= task_id %>").replaceWith(data);
					}
				});
			}
			return false;
		});
	<% end %>
<%- end -%>