config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/redmine-plugin-scrum
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

resources :projects do
  resources :sprints, :shallow => true do
    member do
      get :edit_effort
      put :update_effort
      get :burndown
      get :burndown_graph
    end
    collection do
      get :burndown_index
    end
  end
  post "sprints/change_task_status",
       :controller => :sprints, :action => :change_task_status,
       :as => :sprints_change_task_status

  resources :product_backlog, :shallow => true, :only => [:index] do
    collection do
      post :sort
      post :create_pbi
      get :burndown
      get :burndown_graph
      get :check_dependencies
    end
  end
  get "product_backlog/new_pbi/:tracker_id",
      :controller => :product_backlog, :action => :new_pbi,
      :as => :product_backlog_new_pbi

  get "release_plan",
      :controller => :scrum, :action => :release_plan,
      :as => :release_plan

end

post "issues/:id/story_points",
     :controller => :scrum, :action => :change_story_points,
     :as => :change_story_points
post "issues/:id/pending_effort",
     :controller => :scrum, :action => :change_pending_effort,
     :as => :change_pending_effort
post "issues/:id/assigned_to",
     :controller => :scrum, :action => :change_assigned_to,
     :as => :change_assigned_to
post "issues/:id/create_time_entry",
     :controller => :scrum, :action => :create_time_entry,
     :as => :create_time_entry
get "scrum/:sprint_id/new_pbi/:tracker_id",
     :controller => :scrum, :action => :new_pbi,
     :as => :new_pbi
post "scrum/:sprint_id/create_pbi",
     :controller => :scrum, :action => :create_pbi,
     :as => :create_pbi
get "scrum/:pbi_id/new/:tracker_id",
    :controller => :scrum, :action => :new_task,
    :as => :new_task
post "scrum/:pbi_id/create_task",
     :controller => :scrum, :action => :create_task,
     :as => :create_task
get "scrum/:pbi_id/edit_pbi",
    :controller => :scrum, :action => :edit_pbi,
    :as => :edit_pbi
post "scrum/:pbi_id/update_pbi",
     :controller => :scrum, :action => :update_pbi,
     :as => :update_pbi
get "scrum/:id/edit_task",
    :controller => :scrum, :action => :edit_task,
    :as => :edit_task
post "scrum/:id/update_task",
     :controller => :scrum, :action => :update_task,
     :as => :update_task
post "scrum/:pbi_id/move_to_last_sprint",
     :controller => :scrum, :action => :move_to_last_sprint,
     :as => :move_to_last_sprint
post "scrum/:pbi_id/move_to_product_backlog",
     :controller => :scrum, :action => :move_to_product_backlog,
     :as => :move_to_product_backlog

app/controllers/scrum_controller.rb
# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/redmine-plugin-scrum
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

class ScrumController < ApplicationController

  menu_item :scrum

  before_filter :find_issue, :only => [:change_story_points, :change_pending_effort,
                                       :change_assigned_to, :create_time_entry,
                                       :edit_task, :update_task]
  before_filter :find_sprint, :only => [:new_pbi, :create_pbi]
  before_filter :find_pbi, :only => [:new_task, :create_task, :edit_pbi, :update_pbi,
                                     :move_to_last_sprint, :move_to_product_backlog]
  before_filter :find_project_by_project_id, :only => [:release_plan]
  before_filter :authorize, :except => [:new_pbi, :create_pbi, :new_task, :create_task]
  before_filter :authorize_add_issues, :only => [:new_pbi, :create_pbi, :new_task, :create_task]

  helper :scrum
  helper :timelog
  helper :custom_fields
  helper :projects

  def change_story_points
    begin
      @issue.story_points = params[:value]
      status = 200
    rescue
      status = 503
    end
    render :nothing => true, :status => status
  end

  def change_pending_effort
    @issue.pending_effort = params[:value]
    render :nothing => true, :status => 200
  end

  def change_assigned_to
    @issue.init_journal(User.current)
    @issue.assigned_to = params[:value].blank? ? nil : User.find(params[:value].to_i)
    @issue.save!
    render_task(@project, @issue, params)
  end

  def create_time_entry
    time_entry = TimeEntry.new(params[:time_entry])
    time_entry.project_id = @project.id
    time_entry.issue_id = @issue.id
    time_entry.user_id = params[:time_entry][:user_id]
    call_hook(:controller_timelog_edit_before_save, {:params => params, :time_entry => time_entry})
    time_entry.save!
    render_task(@project, @issue, params)
  end

  def new_pbi
    @pbi = Issue.new
    @pbi.project = @project
    @pbi.tracker = @project.trackers.find(params[:tracker_id])
    @pbi.author = User.current
    @pbi.sprint = @sprint
    @top = !(params[:top].nil?)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create_pbi
    begin
      @continue = !(params[:create_and_continue].nil?)
      @top = !(params[:top].nil?)
      @pbi = Issue.new
      @pbi.project = @project
      @pbi.author = User.current
      @pbi.tracker_id = params[:issue][:tracker_id]
      update_attributes(@pbi, params)
      if @top
        @pbi.set_on_top
        @pbi.save!
      end
      @pbi.sprint = @sprint
      @pbi.save!
    rescue Exception => @exception
      logger.error("Exception: #{@exception.inspect}")
    end
    respond_to do |format|
      format.js
    end
  end

  def edit_pbi
    respond_to do |format|
      format.js
    end
  end

  def update_pbi
    begin
      @pbi.init_journal(User.current, params[:issue][:notes])
      update_attributes(@pbi, params)
      @pbi.save!
    rescue Exception => @exception
      logger.error("Exception: #{@exception.inspect}")
    end
    respond_to do |format|
      format.js
    end
  end

  def move_to_last_sprint
    begin
      raise "The project hasn't defined any Sprint yet" unless @project.last_sprint
      @previous_sprint = @pbi.sprint
      move_issue_to_sprint(@pbi, @project.last_sprint)
    rescue Exception => @exception
      logger.error("Exception: #{@exception.inspect}")
    end
    respond_to do |format|
      format.js
    end
  end

  def move_to_product_backlog
    begin
      raise "The project hasn't defined the Product Backlog yet" unless @project.product_backlog
      move_issue_to_sprint(@pbi, @project.product_backlog)
    rescue Exception => @exception
      logger.error("Exception: #{@exception.inspect}")
    end
    respond_to do |format|
      format.js
    end
  end

  def new_task
    @task = Issue.new
    @task.project = @project
    @task.tracker = Tracker.find(params[:tracker_id])
    @task.parent = @pbi
    @task.author = User.current
    @task.sprint = @sprint
    if Scrum::Setting.inherit_pbi_attributes
      @task.inherit_from_issue(@pbi)
    end
    respond_to do |format|
      format.html
      format.js
    end
  rescue Exception => e
    logger.error("Exception: #{e.inspect}")
    render_404
  end

  def create_task
    begin
      @continue = !(params[:create_and_continue].nil?)
      @task = Issue.new
      @task.project = @project
      @task.parent_issue_id = @pbi.id
      @task.author = User.current
      @task.sprint = @sprint
      @task.tracker_id = params[:issue][:tracker_id]
      update_attributes(@task, params)
      @task.save!
      @task.pending_effort = params[:issue][:pending_effort]
    rescue Exception => @exception
    end
    respond_to do |format|
      format.js
    end
  end

  def edit_task
    respond_to do |format|
      format.js
    end
  end

  def update_task
    begin
      @issue.init_journal(User.current, params[:issue][:notes])
      @old_status = @issue.status
      update_attributes(@issue, params)
      @issue.save!
      @issue.pending_effort = params[:issue][:pending_effort]
    rescue Exception => @exception
      logger.error("Exception: #{@exception.inspect}")
    end
    respond_to do |format|
      format.js
    end
  end

  def release_plan
    @sprints = []
    @story_points_per_sprint, @sprints_count = @project.story_points_per_sprint
    @total_story_points = 0.0
    @pbis_with_estimation = 0
    @pbis_without_estimation = 0
    last_sprint = nil
    versions = {}
    if @project.product_backlog
      @project.product_backlog.pbis.each do |pbi|
        if pbi.story_points
          @pbis_with_estimation += 1
          story_points = pbi.story_points.to_f
          @total_story_points += story_points
          accumulated_story_points = 0.0
          begin
            if last_sprint && last_sprint[:story_points] + story_points > @story_points_per_sprint
              @sprints << last_sprint
              last_sprint = nil
            end
            if last_sprint.nil?
              last_sprint = {:pbis => [], :story_points => 0.0, :versions => []}
            end
            if story_points <= @story_points_per_sprint
              last_sprint[:pbis] << pbi
              last_sprint[:story_points] += accumulated_story_points + story_points
              if pbi.fixed_version
                versions[pbi.fixed_version.id] = {:version => pbi.fixed_version, :sprint => @sprints.count}
              end
            else
              accumulated_story_points += @story_points_per_sprint
            end
            story_points -= @story_points_per_sprint
          end while story_points > 0.0
        else
          @pbis_without_estimation += 1
        end
      end
      if last_sprint
        @sprints << last_sprint
      end
      versions.each_pair do |id, info|
        @sprints[info[:sprint]][:versions] << info[:version]
      end
    end
  end

private

  def render_task(project, task, params)
    render :partial => "post_its/sprint_board/task",
           :status => 200,
           :locals => {:project => project,
                       :task => task,
                       :pbi_status_id => params[:pbi_status_id],
                       :other_pbi_status_ids => params[:other_pbi_status_ids].split(","),
                       :task_id => params[:task_id],
                       :read_only => false}
  end

  def find_sprint
    @sprint = Sprint.find(params[:sprint_id])
    @project = @sprint.project
  rescue
    logger.error("Sprint #{params[:sprint_id]} not found")
    render_404
  end

  def find_pbi
    @pbi = Issue.find(params[:pbi_id])
    @sprint = @pbi.sprint
    @project = @sprint.project
  rescue
    logger.error("PBI #{params[:pbi_id]} not found")
    render_404
  end

  def authorize_add_issues
    if User.current.allowed_to?(:add_issues, @project)
      return true
    else
      render_403
      return false
    end
  end

  def update_attributes(issue, params)
    issue.status_id = params[:issue][:status_id] unless params[:issue][:status_id].nil?
    raise "New status is not allowed" unless issue.new_statuses_allowed_to.include?(issue.status)
    issue.assigned_to_id = params[:issue][:assigned_to_id] unless params[:issue][:assigned_to_id].nil?
    issue.subject = params[:issue][:subject] unless params[:issue][:subject].nil?
    issue.priority_id = params[:issue][:priority_id] unless params[:issue][:priority_id].nil?
    issue.estimated_hours = params[:issue][:estimated_hours] unless params[:issue][:estimated_hours].nil?
    issue.description = params[:issue][:description] unless params[:issue][:description].nil?
    issue.category_id = params[:issue][:category_id] if issue.safe_attribute?(:category_id) and (!(params[:issue][:category_id].nil?))
    issue.fixed_version_id = params[:issue][:fixed_version_id] if issue.safe_attribute?(:fixed_version_id) and (!(params[:issue][:fixed_version_id].nil?))
    issue.start_date = params[:issue][:start_date] if issue.safe_attribute?(:start_date) and (!(params[:issue][:start_date].nil?))
    issue.due_date = params[:issue][:due_date] if issue.safe_attribute?(:due_date) and (!(params[:issue][:due_date].nil?))
    issue.custom_field_values = params[:issue][:custom_field_values] unless params[:issue][:custom_field_values].nil?
  end

  def move_issue_to_sprint(issue, sprint)
    issue.init_journal(User.current)
    issue.sprint = sprint
    issue.save!
    issue.children.each do |child|
      unless child.closed?
        move_issue_to_sprint(child, sprint)
      end
    end
  end

end

app/helpers/scrum_helper.rb
# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/redmine-plugin-scrum
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

module ScrumHelper

  include ProjectsHelper

  def render_hours(hours, options = {})
    if hours.nil?
      ""
    else
      if hours.is_a?(Integer)
        text = ("%d" % hours) unless options[:ignore_zero] and hours == 0
      elsif hours.is_a?(Float)
        text = ("%g" % hours) unless options[:ignore_zero] and hours == 0.0
      else
        text = hours unless options[:ignore_zero] and (hours.blank? or (hours == "0"))
      end
      unless text.blank?
        text = "#{text} h"
        unless options[:link].nil?
          text = link_to(text, options[:link])
        end
        render :inline => "<span title=\"#{options[:title]}\">#{text}</span>"
      end
    end
  end

  def render_pbi_left_header(pbi)
    parts = []
    if Scrum::Setting.render_position_on_pbi
      parts << "#{l(:field_position)}: #{pbi.position}"
    end
    if Scrum::Setting.render_category_on_pbi and pbi.category
      parts << "#{l(:field_category)}: #{h(pbi.category.name)}"
    end
    if Scrum::Setting.render_version_on_pbi and pbi.fixed_version
      parts << "#{l(:field_fixed_version)}: #{link_to_version(pbi.fixed_version)}"
    end
    render :inline => parts.join(", ")
  end

  def render_pbi_right_header(pbi)
    parts = []
    if Scrum::Setting.render_author_on_pbi
      parts << authoring(pbi.created_on, pbi.author)
    end
    if Scrum::Setting.render_updated_on_pbi and pbi.created_on != pbi.updated_on
      parts << "#{l(:label_updated_time, time_tag(pbi.updated_on))}"
    end
    render :inline => parts.join(", ")
  end

end

app/views/scrum/_edit_issue_attributes.html.erb
<%= render :partial => "scrum/issue_attributes", :formats => [:html],
           :locals => {:f => f, :issue => issue} %>

<p class="buttons">
  <%= submit_tag l(:button_edit), :name => "edit", :disable_with => l(:label_loading) %>
  <%= submit_tag l(:button_cancel), :name => nil, :onclick => "hideModal(this);", :type => "button" %>
</p>

app/views/scrum/_edit_pbi_modal.erb
<h3 class="title"><%= "#{@pbi.tracker.name} ##{@pbi.id}" %></h3>

<%- menu_needed = false
    there_is_last_sprint = (!(@project.last_sprint.nil?))
    there_is_product_backlog = (!(@project.product_backlog.nil?))
    render_move_to_last_sprint = (there_is_last_sprint and
                                  ((@pbi.sprint.is_product_backlog?) or (@pbi.sprint.id != @project.last_sprint.id)))
    render_move_to_product_backlog = (there_is_product_backlog and (@pbi.sprint.id != @project.product_backlog.id))
    menu_needed = (render_move_to_last_sprint or render_move_to_product_backlog) -%>
<%- if menu_needed -%>
  <div class="modal-issue-menu">
    <%- if render_move_to_last_sprint -%>
      <%= link_to(l(:label_move_pbi_to_last_sprint), move_to_last_sprint_path(@pbi),
                  :remote => true, :method => :post, :class => "icon icon-sprint-board") %>
    <%- end -%>
    <%- if render_move_to_product_backlog -%>
      <%= link_to(l(:label_move_pbi_to_product_backlog), move_to_product_backlog_path(@pbi),
                  :remote => true, :method => :post, :class => "icon icon-product-backlog") %>
    <%- end -%>
  </div>
<%- end -%>

<div id="messages" />

<%= labelled_form_for @pbi, :url => update_pbi_path(@pbi), :method => :post, :remote => true do |f| %>
  <%= back_url_hidden_field_tag %>
  <%= f.hidden_field :tracker_id, :value => @pbi.tracker_id %>
  <%= f.hidden_field :sprint_id, :value => @pbi.sprint_id %>
  <%= error_messages_for "pbi" %>
  <%= render :partial => "scrum/edit_issue_attributes", :formats => [:html],
             :locals => {:f => f, :issue => @pbi} %>
<% end %>

app/views/scrum/_issue_attributes.html.erb
<div class="box tabular">
  <%- if issue.safe_attribute?(:subject) -%>
    <p>
      <%= f.text_field :subject, :size => 10, :maxlength => 255, :required => true %>
    </p>
  <%- end -%>

  <%- allowed_statuses = issue.new_statuses_allowed_to(User.current) -%>
  <%- if issue.safe_attribute?(:status_id) && allowed_statuses.present? -%>
    <p>
      <%= f.select :status_id, (allowed_statuses.collect {|status| [status.name, status.id]}), {:required => true} %>
    </p>
  <%- end -%>

  <%- if issue.safe_attribute?(:priority_id) -%>
    <p>
      <%= f.select :priority_id, (IssuePriority.active.collect {|p| [p.name, p.id]}), {:required => true, :disabled => !issue.leaf?} %>
    </p>
  <%- end -%>

  <%- if issue.field?(:assigned_to_id) -%>
    <p>
      <%= f.select :assigned_to_id, principals_options_for_select(issue.assignable_users, issue.assigned_to), :include_blank => true, :required => issue.required_attribute?('assigned_to_id') %>
    </p>
  <%- end -%>

  <%- if issue.field?(:category_id) and issue.project.issue_categories.any? -%>
    <p>
      <%= f.select :category_id,
                   (issue.project.issue_categories.collect {|c| [c.name, c.id]}),
                   :include_blank => true,
                   :required => issue.required_attribute?(:category_id) %>
    </p>
  <% end %>

  <%- if issue.field?(:fixed_version_id) and issue.assignable_versions.any? -%>
    <p><%= f.select :fixed_version_id, version_options_for_select(issue.assignable_versions, issue.fixed_version), :include_blank => true, :required => issue.required_attribute?('fixed_version_id') %>
    </p>
  <%- end -%>

  <%- if issue.field?(:start_date) -%>
    <p>
      <%= f.text_field :start_date, :size => 10, :disabled => !issue.leaf?, :required => issue.required_attribute?('start_date') %><%= calendar_for('issue_start_date') if issue.leaf? %>
    </p>
  <%- end -%>

  <%- if issue.field?(:due_date) -%>
    <p>
      <%= f.text_field :due_date, :size => 10, :disabled => !issue.leaf?, :required => issue.required_attribute?('due_date') %><%= calendar_for('issue_due_date') if issue.leaf? %>
    </p>
  <%- end -%>

  <%- if issue.field?(:estimated_hours) -%>
    <p>
      <%= f.text_field :estimated_hours, :size => 4, :maxlength => 10 %>
    </p>
  <%- end -%>

  <%- if issue.is_task? -%>
    <p>
      <%= f.text_field :pending_effort, :size => 4, :maxlength => 10, :label => l(:field_pending_effort) %>
    </p>
  <%- end -%>

  <%- if issue.field?(:done_ratio) and issue.leaf? and Issue.use_field_for_done_ratio? -%>
    <p>
      <%= f.select :done_ratio, ((0..10).to_a.collect {|r| ["#{r * 10} %", r * 10] }), :required => issue.required_attribute?('done_ratio') %>
    </p>
  <%- end -%>

  <%- issue.editable_custom_field_values.each do |value| -%>
    <%- if issue.custom_field?(value.custom_field) -%>
      <p>
        <%= custom_field_tag_with_label :issue, value, :required => value.custom_field.is_required %>
      </p>
    <%- end -%>
  <%- end -%>

  <%- if issue.safe_attribute?(:description) -%>
    <p>
      <%= f.label_for_field :description, :required => issue.required_attribute?(:description) %>
      <%= content_tag :span, :id => "issue_description_and_toolbar" do %>
        <%= f.text_area :description,
                        :cols => 20,
                        :rows => 10,
                        :accesskey => accesskey(:edit),
                        :class => "wiki-edit",
                        :no_label => true %>
      <% end %>
    </p>
  <%- end -%>

  <%- if issue.id -%>
    <p>
      <%= f.text_area :notes, :cols => 60, :rows => 5, :class => "wiki-edit" %>
    </p>
  <%- end -%>
</div>

app/views/scrum/_new_issue_attributes.html.erb
  <div class="box tabular">
    <%- if issue.safe_attribute?(:subject) -%>
      <p>
        <%= f.text_field :subject, :size => 10, :maxlength => 255, :required => true %>
      </p>
    <%- end -%>

    <%- if issue.safe_attribute?(:priority_id) -%>
      <p>
        <%= f.select :priority_id, (IssuePriority.active.collect {|p| [p.name, p.id]}), {:required => true, :disabled => !issue.leaf?} %>
      </p>
    <%- end -%>

    <%- if issue.field?(:assigned_to_id) -%>
      <p>
        <%= f.select :assigned_to_id, principals_options_for_select(issue.assignable_users, issue.assigned_to), :include_blank => true, :required => issue.required_attribute?('assigned_to_id') %>
      </p>
    <%- end -%>

    <%- if issue.field?(:category_id) and issue.project.issue_categories.any? -%>
      <p>
        <%= f.select :category_id,
                     (issue.project.issue_categories.collect {|c| [c.name, c.id]}),
                     :include_blank => true,
                     :required => issue.required_attribute?(:category_id) %>
      </p>
    <% end %>

    <%- if issue.field?(:fixed_version_id) and issue.assignable_versions.any? -%>
      <p><%= f.select :fixed_version_id, version_options_for_select(issue.assignable_versions, issue.fixed_version), :include_blank => true, :required => issue.required_attribute?('fixed_version_id') %>
      </p>
    <%- end -%>

    <%- if issue.field?(:start_date) -%>
      <p>
        <%= f.text_field :start_date, :size => 10, :disabled => !issue.leaf?, :required => issue.required_attribute?('start_date') %><%= calendar_for('issue_start_date') if issue.leaf? %>
      </p>
    <%- end -%>

    <%- if issue.field?(:due_date) -%>
      <p>
        <%= f.text_field :due_date, :size => 10, :disabled => !issue.leaf?, :required => issue.required_attribute?('due_date') %><%= calendar_for('issue_due_date') if issue.leaf? %>
      </p>
    <%- end -%>

    <%- if issue.field?(:estimated_hours) -%>
      <p>
        <%= f.text_field :estimated_hours, :size => 4, :maxlength => 10 %>
      </p>
    <%- end -%>

    <%- if issue.is_task? -%>
      <p>
        <%= f.text_field :pending_effort, :size => 4, :maxlength => 10, :label => l(:field_pending_effort) %>
      </p>
    <%- end -%>

    <%- if issue.field?(:done_ratio) and issue.leaf? and Issue.use_field_for_done_ratio? -%>
      <p>
        <%= f.select :done_ratio, ((0..10).to_a.collect {|r| ["#{r * 10} %", r * 10] }), :required => issue.required_attribute?('done_ratio') %>
      </p>
    <%- end -%>

    <%- issue.editable_custom_field_values.each do |value| -%>
      <%- if issue.custom_field?(value.custom_field) -%>
        <p>
          <%= custom_field_tag_with_label :issue, value, :required => value.custom_field.is_required %>
        </p>
      <%- end -%>
    <%- end -%>

    <%- if issue.safe_attribute?(:description) -%>
      <p>
        <%= f.label_for_field :description, :required => issue.required_attribute?(:description) %>
        <%= content_tag :span, :id => "issue_description_and_toolbar" do %>
          <%= f.text_area :description,
                          :cols => 20,
                          :rows => 10,
                          :accesskey => accesskey(:edit),
                          :class => "wiki-edit",
                          :no_label => true %>
        <% end %>
      </p>
    <%- end -%>
  </div>

  <p class="buttons">
    <%= submit_tag l(:button_create_and_continue), :name => "create_and_continue" %>
    <%= submit_tag l(:button_create), :name => "create" %>
    <%= submit_tag l(:button_cancel), :name => nil, :onclick => "hideModal(this);", :type => "button" %>
  </p>

app/views/scrum/_new_task_modal.html.erb
<h3 class="title"><%= @task.tracker.name %></h3>

<div id="messages" />

<%= labelled_form_for @task, :url => create_task_path(@pbi), :remote => true do |f| %>
  <%= back_url_hidden_field_tag %>
  <%= f.hidden_field :tracker_id, :value => @task.tracker_id %>
  <%= error_messages_for "task" %>
  <%= render :partial => "scrum/new_issue_attributes", :formats => [:html],
             :locals => {:f => f, :issue => @task} %>
<% end %>

app/views/scrum/_release_plan_head.html.erb
<table class="box attributes">
  <tr>
    <td>
      <%= l(:label_sps_per_sprint_stat, :count => sprints_count, :sps => sps_per_sprint) %>
    </td>
  </tr>
  <tr>
    <td>
      <%= l(:label_release_plan_stats,
            :sps => total_story_points,
            :pbis => pbis_with_estimation,
            :pbis_without_sps => pbis_without_estimation) %>
    </td>
  </tr>
</table>

app/views/scrum/create_pbi.js.erb
<%- if @continue or defined?(@exception) -%>
	<%- if defined?(@exception) -%>
		<%- message = l(:error_creating_pbi, :message => @exception.message)
				message_class = "error" -%>
	<%- else -%>
		$("#new_issue").each (function() {
			this.reset();
		});
		<%- message = l(:notice_pbi_created)
				message_class = "notice" -%>
	<%- end -%>
	$("#messages").html("<div class=\"flash <%= message_class %>\"><%= message %></div>");
<%- else -%>
	$("#ajax-modal").dialog("close");
<%- end -%>
<%- if !defined?(@exception) -%>
	if ($("#pbis").length > 0) {
		<%- if @top -%>
			$("#pbis").prepend("<%=
				escape_javascript(render :partial => "post_its/product_backlog/pbi", :formats => [:html],
																 :locals => {:project => @project, :pbi => @pbi, :read_only => false}).html_safe
			%>");
		<%- else -%>
			$("#pbis").append("<%=
				escape_javascript(render :partial => "post_its/product_backlog/pbi", :formats => [:html],
																 :locals => {:project => @project, :pbi => @pbi, :read_only => false}).html_safe
			%>");
		<%- end -%>
	} else if ($("#sprint_board").length > 0) {
		$("#sprint_board").append("<%=
			escape_javascript(render :partial => "post_its/sprint_board/pbi_row", :formats => [:html],
															 :locals => {:project => @project, :pbi => @pbi,
																					 :task_statuses => IssueStatus.task_statuses}).html_safe
		%>");
	}
  <%- if (!(IssueStatus.pbi_statuses.include?(@pbi.status))) -%>
    $("#<%= @pbi.sprint.is_product_backlog? ? "pbi_#{@pbi.id}" : "pbi_#{@pbi.id}_row" %>").remove();
  <%- end -%>
<%- end -%>

app/views/scrum/edit_task.js.erb
$("#ajax-modal").html("<%= escape_javascript(render :partial => "scrum/edit_task_modal") %>");
showModal("ajax-modal", "800px");

app/views/scrum/move_to_product_backlog.js.erb
<%- if defined?(@exception) -%>
  <%- message = l(:error_updating_pbi, :message => @exception.message)
      message_class = "error" -%>
  $("#messages").html("<div class=\"flash <%= message_class %>\"><%= message %></div>");
<%- else -%>
  $("#ajax-modal").dialog("close");
  $("#<%= "pbi_#{@pbi.id}_row" %>").remove();
<%- end -%>