config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/redmine-plugin-scrum
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

resources :projects do
  resources :sprints, :shallow => true do
    member do
      get :edit_effort
      put :update_effort
      get :burndown
      get :burndown_graph
    end
    collection do
      get :burndown_index
    end
  end
  post "sprints/change_task_status",
       :controller => :sprints, :action => :change_task_status,
       :as => :sprints_change_task_status

  resources :product_backlog, :shallow => true, :only => [:index] do
    collection do
      post :sort
      post :create_pbi
      get :burndown
      get :burndown_graph
      get :check_dependencies
    end
  end
  get "product_backlog/new_pbi/:tracker_id",
      :controller => :product_backlog, :action => :new_pbi,
      :as => :product_backlog_new_pbi

  get "release_plan",
      :controller => :scrum, :action => :release_plan,
      :as => :release_plan

end

post "issues/:id/story_points",
     :controller => :scrum, :action => :change_story_points,
     :as => :change_story_points
post "issues/:id/pending_effort",
     :controller => :scrum, :action => :change_pending_effort,
     :as => :change_pending_effort
post "issues/:id/assigned_to",
     :controller => :scrum, :action => :change_assigned_to,
     :as => :change_assigned_to
post "issues/:id/create_time_entry",
     :controller => :scrum, :action => :create_time_entry,
     :as => :create_time_entry
get "scrum/:sprint_id/new_pbi/:tracker_id",
     :controller => :scrum, :action => :new_pbi,
     :as => :new_pbi
post "scrum/:sprint_id/create_pbi",
     :controller => :scrum, :action => :create_pbi,
     :as => :create_pbi
get "scrum/:pbi_id/new/:tracker_id",
    :controller => :scrum, :action => :new_task,
    :as => :new_task
post "scrum/:pbi_id/create_task",
     :controller => :scrum, :action => :create_task,
     :as => :create_task
get "scrum/:pbi_id/edit_pbi",
    :controller => :scrum, :action => :edit_pbi,
    :as => :edit_pbi
post "scrum/:pbi_id/update_pbi",
     :controller => :scrum, :action => :update_pbi,
     :as => :update_pbi
get "scrum/:id/edit_task",
    :controller => :scrum, :action => :edit_task,
    :as => :edit_task
post "scrum/:id/update_task",
     :controller => :scrum, :action => :update_task,
     :as => :update_task
post "scrum/:pbi_id/move_to_last_sprint",
     :controller => :scrum, :action => :move_to_last_sprint,
     :as => :move_to_last_sprint
post "scrum/:pbi_id/move_to_product_backlog",
     :controller => :scrum, :action => :move_to_product_backlog,
     :as => :move_to_product_backlog

app/views/common/_scrum_editable_value.html.erb
<input id="<%= element_id %>" type="text" class="editable-time" size="2"
       title="<%= title %>" value="<%= value %>" <%= "readonly" unless editable %> />

<%- if editable -%>
  <%= javascript_tag do %>
    $(document).ready(function() {
      $("#<%= element_id %>").change(function() {
        if ($.isFunction($.fn.setupAjaxIndicator)) {
          setupAjaxIndicator();
        }
        $.ajax({
          url: "<%= change_element_path %>",
          type: "POST",
          data: {value: $(this).val()},
          error: function() {
            alert("<%= l(:error_changing_value) %>");
          },
          complete: function() {
            if ($.isFunction($.fn.hideOnLoad)) {
              hideOnLoad();
            }
          }
        });
      });
    });
  <% end %>
<%- end -%>

app/views/common/_scrum_footer.html.erb
<%= javascript_tag do %>
  $(document).ready(function() {
    <%- link = link_to(l(:label_scrum), Redmine::Plugin::registered_plugins[:scrum].url)
        author = Redmine::Plugin::registered_plugins[:scrum].author
        copy_right = link_to("©", "http://creativecommons.org/licenses/by-nd/4.0/")
        legend = "Powered by #{link} plugin #{copy_right} 2013-2014 #{author}" -%>
    $("#footer").append('<div class="bgl"><div class="bgr"><%= raw legend %></div></div>');
  });
<% end %>

app/views/common/_scrum_menu.html.erb
<div class="contextual">
  <%- if User.current.allowed_to?(:view_sprint_board, @project) -%>
    <%= link_to(l(:label_sprint_board), project_sprints_path(@project),
                :class => "icon icon-sprint-board") %>
  <%- end -%>
  <%- if User.current.allowed_to?(:view_sprint_burndown, @project) -%>
    <%= link_to(l(:label_sprint_burndown_chart), burndown_index_project_sprints_path(@project),
                :class => "icon icon-burndown") %>
  <%- end -%>
  <%- if User.current.allowed_to?(:view_product_backlog, @project) -%>
    <%= link_to(l(:label_product_backlog), project_product_backlog_index_path(@project),
                :class => "icon icon-product-backlog") %>
  <%- end -%>
  <%- if User.current.allowed_to?(:view_product_backlog_burndown, @project) -%>
    <%= link_to(l(:label_product_backlog_burndown_chart), burndown_project_product_backlog_index_path(@project),
                :class => "icon icon-burndown") %>
  <%- end -%>
  <%- if User.current.allowed_to?(:view_release_plan, @project) -%>
    <%= link_to(l(:label_release_plan), project_release_plan_path(@project),
                :class => "icon icon-release-plan") %>
  <%- end -%>
</div>

app/views/common/_scrum_pending_effort.html.erb
<%= render :partial => "common/scrum_editable_value",
           :locals => {:project => project,
                       :title => l(:field_pending_effort),
                       :element_id => "pending_effort_#{task.id}",
                       :value => task.pending_effort,
                       :editable => (User.current.allowed_to?(:edit_sprint_board, project) and
                                     task.editable?),
                       :change_element_path => change_pending_effort_path(task)} %>

app/views/common/_scrum_story_points.html.erb
<%= render :partial => "common/scrum_editable_value",
           :locals => {:project => project,
                       :title => l(:label_story_point_plural),
                       :element_id => "story_points_#{pbi.id}",
                       :value => pbi.story_points,
                       :editable => (User.current.allowed_to?(:edit_product_backlog, project) and
                                     pbi.editable? and !read_only),
                       :change_element_path => change_story_points_path(pbi)} %>